import { RoleProfile, ROLE_ENGINE_VERSION } from "./role.types";

export const CANONICAL_ROLE_CATALOG: RoleProfile[] = [
  // ──────────────── FULL-STACK ENGINEER ────────────────
  {
    roleId: "role_fullstack_engineer",
    title: "Full-Stack Engineer",
    aliases: [
      "Full-Stack Engineer",
      "Full Stack Engineer",
      "Full Stack Developer",
      "Full-Stack Developer",
      "Fullstack Developer",
      "Software Engineer — Full Stack",
      "Full Stack Web Developer",
    ],
    seniority: { level: "MID", minYears: 2, maxYears: 6 },
    requiredSkills: [
      { skillId: "skill_react", canonicalName: "React", importance: "REQUIRED", category: "FRONTEND" },
      { skillId: "skill_nextjs", canonicalName: "Next.js", importance: "REQUIRED", category: "FRONTEND" },
      { skillId: "skill_typescript", canonicalName: "TypeScript", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_nodejs", canonicalName: "Node.js", importance: "REQUIRED", category: "BACKEND" },
      { skillId: "skill_rest_apis", canonicalName: "REST APIs", importance: "REQUIRED", category: "BACKEND" },
      { skillId: "skill_sql", canonicalName: "SQL", importance: "REQUIRED", category: "DATABASE" },
      { skillId: "skill_git", canonicalName: "Git", importance: "REQUIRED", category: "TOOLS" },
    ],
    preferredSkills: [
      { skillId: "skill_aws", canonicalName: "AWS", importance: "PREFERRED", category: "CLOUD" },
      { skillId: "skill_docker", canonicalName: "Docker", importance: "PREFERRED", category: "DEVOPS" },
      { skillId: "skill_postgresql", canonicalName: "PostgreSQL", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_mongodb", canonicalName: "MongoDB", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_tailwind", canonicalName: "Tailwind CSS", importance: "PREFERRED", category: "FRONTEND" },
      { skillId: "skill_cicd", canonicalName: "CI/CD", importance: "PREFERRED", category: "DEVOPS" },
      { skillId: "skill_redis", canonicalName: "Redis", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_graphql", canonicalName: "GraphQL", importance: "PREFERRED", category: "BACKEND" },
    ],
    responsibilities: [
      "Architect and build high-performance client-side web applications",
      "Design and maintain scalable backend REST APIs and microservices",
      "Model and optimize relational and NoSQL database schemas",
      "Deploy and maintain applications across cloud and containerized infrastructure",
    ],
    experienceRequirements: [{ minYears: 2, category: "Full-Stack Web Development", requirementType: "REQUIRED" }],
    education: [{ degreeLevel: "BACHELORS", fieldOfStudy: "Computer Science or related field", requirementType: "PREFERRED" }],
    domains: ["SaaS", "E-commerce", "Web Applications"],
    keywords: ["microservices", "scalable", "full stack", "distributed systems", "RESTful", "cloud"],
    version: ROLE_ENGINE_VERSION,
  },

  // ──────────────── FRONTEND ENGINEER ────────────────
  {
    roleId: "role_frontend_engineer",
    title: "Frontend Engineer",
    aliases: [
      "Frontend Engineer",
      "Front-End Engineer",
      "Frontend Developer",
      "Front-End Developer",
      "React Developer",
      "UI Engineer",
      "Client-Side Engineer",
    ],
    seniority: { level: "MID", minYears: 2, maxYears: 5 },
    requiredSkills: [
      { skillId: "skill_react", canonicalName: "React", importance: "REQUIRED", category: "FRONTEND" },
      { skillId: "skill_typescript", canonicalName: "TypeScript", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_javascript", canonicalName: "JavaScript", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_html_css", canonicalName: "HTML/CSS", importance: "REQUIRED", category: "FRONTEND" },
      { skillId: "skill_nextjs", canonicalName: "Next.js", importance: "REQUIRED", category: "FRONTEND" },
      { skillId: "skill_tailwind", canonicalName: "Tailwind CSS", importance: "REQUIRED", category: "FRONTEND" },
    ],
    preferredSkills: [
      { skillId: "skill_redux", canonicalName: "Redux", importance: "PREFERRED", category: "FRONTEND" },
      { skillId: "skill_gsap", canonicalName: "GSAP", importance: "PREFERRED", category: "FRONTEND" },
      { skillId: "skill_vue", canonicalName: "Vue.js", importance: "PREFERRED", category: "FRONTEND" },
      { skillId: "skill_testing", canonicalName: "Automated Testing", importance: "PREFERRED", category: "TESTING" },
      { skillId: "skill_rest_apis", canonicalName: "REST APIs", importance: "PREFERRED", category: "BACKEND" },
      { skillId: "skill_vercel", canonicalName: "Vercel", importance: "PREFERRED", category: "CLOUD" },
    ],
    responsibilities: [
      "Develop responsive, accessible, and performant user interfaces",
      "Translate Figma/UI designs into high-fidelity modular React/Next.js components",
      "Optimize web performance, Core Web Vitals, and client-side rendering speed",
      "Implement client-side state management and REST API integrations",
    ],
    experienceRequirements: [{ minYears: 2, category: "Frontend Web Development", requirementType: "REQUIRED" }],
    education: [{ degreeLevel: "BACHELORS", fieldOfStudy: "Computer Science or related field", requirementType: "PREFERRED" }],
    domains: ["Web Design", "Interactive Applications", "Design Systems"],
    keywords: ["responsive", "accessibility", "state management", "Core Web Vitals", "animations"],
    version: ROLE_ENGINE_VERSION,
  },

  // ──────────────── BACKEND ENGINEER ────────────────
  {
    roleId: "role_backend_engineer",
    title: "Backend Engineer",
    aliases: [
      "Backend Engineer",
      "Back-End Engineer",
      "Backend Developer",
      "Back-End Developer",
      "Node.js Developer",
      "API Engineer",
      "Server Engineer",
    ],
    seniority: { level: "MID", minYears: 2, maxYears: 6 },
    requiredSkills: [
      { skillId: "skill_nodejs", canonicalName: "Node.js", importance: "REQUIRED", category: "BACKEND" },
      { skillId: "skill_express", canonicalName: "Express.js", importance: "REQUIRED", category: "BACKEND" },
      { skillId: "skill_rest_apis", canonicalName: "REST APIs", importance: "REQUIRED", category: "BACKEND" },
      { skillId: "skill_postgresql", canonicalName: "PostgreSQL", importance: "REQUIRED", category: "DATABASE" },
      { skillId: "skill_sql", canonicalName: "SQL", importance: "REQUIRED", category: "DATABASE" },
      { skillId: "skill_git", canonicalName: "Git", importance: "REQUIRED", category: "TOOLS" },
    ],
    preferredSkills: [
      { skillId: "skill_mongodb", canonicalName: "MongoDB", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_redis", canonicalName: "Redis", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_docker", canonicalName: "Docker", importance: "PREFERRED", category: "DEVOPS" },
      { skillId: "skill_aws", canonicalName: "AWS", importance: "PREFERRED", category: "CLOUD" },
      { skillId: "skill_fastapi", canonicalName: "FastAPI", importance: "PREFERRED", category: "BACKEND" },
      { skillId: "skill_python", canonicalName: "Python", importance: "PREFERRED", category: "LANGUAGE" },
      { skillId: "skill_graphql", canonicalName: "GraphQL", importance: "PREFERRED", category: "BACKEND" },
      { skillId: "skill_jwt", canonicalName: "JWT", importance: "PREFERRED", category: "SECURITY" },
    ],
    responsibilities: [
      "Architect, build, and scale resilient server-side microservices",
      "Design database schema migrations, query indexes, and caching strategies",
      "Implement secure authentication, authorization, and API rate limiting",
      "Optimize throughput, latency, and fault tolerance for critical business endpoints",
    ],
    experienceRequirements: [{ minYears: 2, category: "Backend / Distributed Systems", requirementType: "REQUIRED" }],
    education: [{ degreeLevel: "BACHELORS", fieldOfStudy: "Computer Science or related field", requirementType: "PREFERRED" }],
    domains: ["Cloud Platforms", "Microservices", "High-Throughput Systems"],
    keywords: ["microservices", "latency", "concurrency", "indexing", "caching", "throughput"],
    version: ROLE_ENGINE_VERSION,
  },

  // ──────────────── DEVOPS & CLOUD ENGINEER ────────────────
  {
    roleId: "role_devops_cloud_engineer",
    title: "DevOps & Cloud Engineer",
    aliases: [
      "DevOps & Cloud Engineer",
      "DevOps Engineer",
      "Cloud Engineer",
      "Site Reliability Engineer",
      "SRE",
      "Infrastructure Engineer",
      "Platform Engineer",
    ],
    seniority: { level: "MID", minYears: 3, maxYears: 7 },
    requiredSkills: [
      { skillId: "skill_aws", canonicalName: "AWS", importance: "REQUIRED", category: "CLOUD" },
      { skillId: "skill_docker", canonicalName: "Docker", importance: "REQUIRED", category: "DEVOPS" },
      { skillId: "skill_cicd", canonicalName: "CI/CD", importance: "REQUIRED", category: "DEVOPS" },
      { skillId: "skill_linux", canonicalName: "Linux", importance: "REQUIRED", category: "DEVOPS" },
      { skillId: "skill_git", canonicalName: "Git", importance: "REQUIRED", category: "TOOLS" },
    ],
    preferredSkills: [
      { skillId: "skill_kubernetes", canonicalName: "Kubernetes", importance: "PREFERRED", category: "DEVOPS" },
      { skillId: "skill_terraform", canonicalName: "Terraform", importance: "PREFERRED", category: "DEVOPS" },
      { skillId: "skill_cloud_architecture", canonicalName: "Cloud Architecture", importance: "PREFERRED", category: "CLOUD" },
      { skillId: "skill_gcp", canonicalName: "GCP", importance: "PREFERRED", category: "CLOUD" },
      { skillId: "skill_azure", canonicalName: "Azure", importance: "PREFERRED", category: "CLOUD" },
      { skillId: "skill_serverless", canonicalName: "Serverless", importance: "PREFERRED", category: "CLOUD" },
      { skillId: "skill_nginx", canonicalName: "Nginx", importance: "PREFERRED", category: "DEVOPS" },
    ],
    responsibilities: [
      "Build and automate CI/CD release pipelines and infrastructure as code (IaC)",
      "Manage container orchestration with Docker and Kubernetes clusters",
      "Monitor system health, logging, metrics, and incident response automation",
      "Enforce cloud security, IAM policies, and infrastructure cost optimization",
    ],
    experienceRequirements: [{ minYears: 3, category: "DevOps / Cloud Infrastructure", requirementType: "REQUIRED" }],
    education: [{ degreeLevel: "BACHELORS", fieldOfStudy: "Computer Science or related field", requirementType: "PREFERRED" }],
    domains: ["Cloud Infrastructure", "Kubernetes", "Site Reliability"],
    keywords: ["automation", "IaC", "CI/CD", "observability", "containers", "uptime"],
    version: ROLE_ENGINE_VERSION,
  },

  // ──────────────── AI/ML ENGINEER ────────────────
  {
    roleId: "role_aiml_engineer",
    title: "AI/ML Engineer",
    aliases: [
      "AI/ML Engineer",
      "AI/ML Specialist",
      "Machine Learning Engineer",
      "AI Engineer",
      "MLOps Engineer",
      "Data Scientist",
    ],
    seniority: { level: "MID", minYears: 2, maxYears: 6 },
    requiredSkills: [
      { skillId: "skill_python", canonicalName: "Python", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_aiml", canonicalName: "AI/ML", importance: "REQUIRED", category: "AI_ML" },
      { skillId: "skill_rest_apis", canonicalName: "REST APIs", importance: "REQUIRED", category: "BACKEND" },
      { skillId: "skill_sql", canonicalName: "SQL", importance: "REQUIRED", category: "DATABASE" },
    ],
    preferredSkills: [
      { skillId: "skill_fastapi", canonicalName: "FastAPI", importance: "PREFERRED", category: "BACKEND" },
      { skillId: "skill_postgresql", canonicalName: "PostgreSQL", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_docker", canonicalName: "Docker", importance: "PREFERRED", category: "DEVOPS" },
      { skillId: "skill_aws", canonicalName: "AWS", importance: "PREFERRED", category: "CLOUD" },
      { skillId: "skill_git", canonicalName: "Git", importance: "PREFERRED", category: "TOOLS" },
    ],
    responsibilities: [
      "Develop and fine-tune machine learning and LLM agent pipelines",
      "Build high-throughput inference APIs with FastAPI and Python",
      "Manage dataset preprocessing, feature engineering, and model evaluation",
      "Deploy AI models to scalable cloud and serverless endpoints",
    ],
    experienceRequirements: [{ minYears: 2, category: "Applied AI / Machine Learning", requirementType: "REQUIRED" }],
    education: [{ degreeLevel: "BACHELORS", fieldOfStudy: "Computer Science, Data Science, or Mathematics", requirementType: "REQUIRED" }],
    domains: ["Artificial Intelligence", "LLMs", "Predictive Modeling"],
    keywords: ["LLM", "deep learning", "inference", "embeddings", "vector search", "model training"],
    version: ROLE_ENGINE_VERSION,
  },

  // ──────────────── MOBILE DEVELOPER ────────────────
  {
    roleId: "role_mobile_developer",
    title: "Mobile App Developer",
    aliases: [
      "Mobile App Developer",
      "Mobile Developer",
      "Mobile Engineer",
      "React Native Developer",
      "iOS Developer",
      "Android Developer",
      "Flutter Developer",
    ],
    seniority: { level: "MID", minYears: 2, maxYears: 5 },
    requiredSkills: [
      { skillId: "skill_react", canonicalName: "React", importance: "REQUIRED", category: "FRONTEND" },
      { skillId: "skill_react_native", canonicalName: "React Native", importance: "REQUIRED", category: "MOBILE" },
      { skillId: "skill_typescript", canonicalName: "TypeScript", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_javascript", canonicalName: "JavaScript", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_git", canonicalName: "Git", importance: "REQUIRED", category: "TOOLS" },
    ],
    preferredSkills: [
      { skillId: "skill_flutter", canonicalName: "Flutter", importance: "PREFERRED", category: "MOBILE" },
      { skillId: "skill_swift", canonicalName: "Swift", importance: "PREFERRED", category: "MOBILE" },
      { skillId: "skill_kotlin", canonicalName: "Kotlin", importance: "PREFERRED", category: "MOBILE" },
      { skillId: "skill_firebase", canonicalName: "Firebase", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_rest_apis", canonicalName: "REST APIs", importance: "PREFERRED", category: "BACKEND" },
      { skillId: "skill_testing", canonicalName: "Automated Testing", importance: "PREFERRED", category: "TESTING" },
    ],
    responsibilities: [
      "Build and publish cross-platform iOS and Android mobile applications",
      "Integrate native device modules, push notifications, and offline storage",
      "Optimize app render frame rates, memory usage, and battery performance",
      "Coordinate app submissions to Apple App Store and Google Play Store",
    ],
    experienceRequirements: [{ minYears: 2, category: "Mobile Application Development", requirementType: "REQUIRED" }],
    education: [{ degreeLevel: "BACHELORS", fieldOfStudy: "Computer Science or related field", requirementType: "PREFERRED" }],
    domains: ["Mobile Apps", "iOS & Android", "Cross-Platform"],
    keywords: ["cross-platform", "offline storage", "push notifications", "App Store", "Play Store"],
    version: ROLE_ENGINE_VERSION,
  },

  // ──────────────── GENERIC SOFTWARE ENGINEER (SAFE FALLBACK) ────────────────
  {
    roleId: "role_generic_software_engineer",
    title: "Software Engineer",
    aliases: [
      "Software Engineer",
      "Software Developer",
      "Programmer",
      "Application Developer",
      "Member of Technical Staff",
    ],
    seniority: { level: "MID", minYears: 2, maxYears: 5 },
    requiredSkills: [
      { skillId: "skill_javascript", canonicalName: "JavaScript", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_typescript", canonicalName: "TypeScript", importance: "REQUIRED", category: "LANGUAGE" },
      { skillId: "skill_rest_apis", canonicalName: "REST APIs", importance: "REQUIRED", category: "BACKEND" },
      { skillId: "skill_git", canonicalName: "Git", importance: "REQUIRED", category: "TOOLS" },
    ],
    preferredSkills: [
      { skillId: "skill_react", canonicalName: "React", importance: "PREFERRED", category: "FRONTEND" },
      { skillId: "skill_nodejs", canonicalName: "Node.js", importance: "PREFERRED", category: "BACKEND" },
      { skillId: "skill_sql", canonicalName: "SQL", importance: "PREFERRED", category: "DATABASE" },
      { skillId: "skill_docker", canonicalName: "Docker", importance: "PREFERRED", category: "DEVOPS" },
    ],
    responsibilities: [
      "Design, develop, test, and deploy production software applications",
      "Collaborate in cross-functional agile teams through code reviews and documentation",
      "Debug, profile, and resolve complex technical defects and performance bottlenecks",
    ],
    experienceRequirements: [{ minYears: 2, category: "Software Development", requirementType: "REQUIRED" }],
    education: [{ degreeLevel: "BACHELORS", fieldOfStudy: "Computer Science or related field", requirementType: "PREFERRED" }],
    domains: ["Software Engineering"],
    keywords: ["algorithms", "clean code", "testing", "agile", "collaboration"],
    version: ROLE_ENGINE_VERSION,
  },
];
