import { SkillDefinition } from "./skill.types";

export const CANONICAL_SKILL_CATALOG: SkillDefinition[] = [
  // ──────────────── FRONTEND ────────────────
  {
    id: "skill_react",
    canonicalName: "React",
    displayName: "React.js",
    aliases: ["React", "React.js", "ReactJS", "React 18", "React 19"],
    category: "FRONTEND",
    parentSkillId: "skill_javascript",
    relatedSkillIds: ["skill_nextjs", "skill_redux", "skill_react_native"],
    active: true,
  },
  {
    id: "skill_nextjs",
    canonicalName: "Next.js",
    displayName: "Next.js Framework",
    aliases: ["Next.js", "NextJS", "Next.js 14", "Next.js 15", "Next js"],
    category: "FRONTEND",
    parentSkillId: "skill_react",
    relatedSkillIds: ["skill_react", "skill_typescript", "skill_tailwind"],
    active: true,
  },
  {
    id: "skill_typescript",
    canonicalName: "TypeScript",
    displayName: "TypeScript",
    aliases: ["TypeScript", "TS"],
    category: "LANGUAGE",
    parentSkillId: "skill_javascript",
    relatedSkillIds: ["skill_javascript", "skill_react", "skill_nodejs"],
    active: true,
  },
  {
    id: "skill_javascript",
    canonicalName: "JavaScript",
    displayName: "JavaScript",
    aliases: ["JavaScript", "JS", "ES6", "ECMAScript", "ES6+"],
    category: "LANGUAGE",
    relatedSkillIds: ["skill_typescript", "skill_react", "skill_nodejs"],
    active: true,
  },
  {
    id: "skill_html_css",
    canonicalName: "HTML/CSS",
    displayName: "HTML5 & CSS3",
    aliases: ["HTML/CSS", "HTML", "HTML5", "CSS", "CSS3"],
    category: "FRONTEND",
    relatedSkillIds: ["skill_tailwind", "skill_sass"],
    active: true,
  },
  {
    id: "skill_tailwind",
    canonicalName: "Tailwind CSS",
    displayName: "Tailwind CSS",
    aliases: ["Tailwind CSS", "TailwindCSS", "Tailwind"],
    category: "FRONTEND",
    parentSkillId: "skill_html_css",
    relatedSkillIds: ["skill_html_css", "skill_nextjs"],
    active: true,
  },
  {
    id: "skill_redux",
    canonicalName: "Redux",
    displayName: "Redux Toolkit",
    aliases: ["Redux", "Redux Toolkit", "RTK"],
    category: "FRONTEND",
    parentSkillId: "skill_react",
    relatedSkillIds: ["skill_react", "skill_zustand"],
    active: true,
  },
  {
    id: "skill_gsap",
    canonicalName: "GSAP",
    displayName: "GreenSock (GSAP)",
    aliases: ["GSAP", "GreenSock"],
    category: "FRONTEND",
    relatedSkillIds: ["skill_javascript", "skill_framer_motion"],
    active: true,
  },
  {
    id: "skill_vue",
    canonicalName: "Vue.js",
    displayName: "Vue.js",
    aliases: ["Vue", "Vue.js", "VueJS", "Vue 3", "Nuxt", "Nuxt.js"],
    category: "FRONTEND",
    parentSkillId: "skill_javascript",
    relatedSkillIds: ["skill_react", "skill_angular"],
    active: true,
  },
  {
    id: "skill_angular",
    canonicalName: "Angular",
    displayName: "Angular",
    aliases: ["Angular", "AngularJS", "Angular 17", "Angular 18"],
    category: "FRONTEND",
    parentSkillId: "skill_typescript",
    relatedSkillIds: ["skill_typescript", "skill_react"],
    active: true,
  },

  // ──────────────── BACKEND ────────────────
  {
    id: "skill_nodejs",
    canonicalName: "Node.js",
    displayName: "Node.js Runtime",
    aliases: ["Node.js", "NodeJS", "Node", "Node js"],
    category: "BACKEND",
    parentSkillId: "skill_javascript",
    relatedSkillIds: ["skill_express", "skill_nestjs"],
    active: true,
  },
  {
    id: "skill_express",
    canonicalName: "Express.js",
    displayName: "Express.js",
    aliases: ["Express.js", "ExpressJS", "Express", "Express js"],
    category: "BACKEND",
    parentSkillId: "skill_nodejs",
    relatedSkillIds: ["skill_nodejs", "skill_rest_apis"],
    active: true,
  },
  {
    id: "skill_rest_apis",
    canonicalName: "REST APIs",
    displayName: "RESTful API Architecture",
    aliases: ["REST APIs", "REST API", "RESTful APIs", "REST", "RESTful Web Services"],
    category: "BACKEND",
    relatedSkillIds: ["skill_graphql", "skill_express"],
    active: true,
  },
  {
    id: "skill_graphql",
    canonicalName: "GraphQL",
    displayName: "GraphQL",
    aliases: ["GraphQL", "Apollo GraphQL", "Apollo"],
    category: "BACKEND",
    relatedSkillIds: ["skill_rest_apis", "skill_nodejs"],
    active: true,
  },
  {
    id: "skill_jwt",
    canonicalName: "JWT",
    displayName: "JSON Web Tokens (JWT)",
    aliases: ["JWT", "JSON Web Tokens", "OAuth", "OAuth 2.0"],
    category: "SECURITY",
    relatedSkillIds: ["skill_nodejs", "skill_rest_apis"],
    active: true,
  },
  {
    id: "skill_python",
    canonicalName: "Python",
    displayName: "Python",
    aliases: ["Python", "Python 3", "Python3"],
    category: "LANGUAGE",
    relatedSkillIds: ["skill_fastapi", "skill_django"],
    active: true,
  },
  {
    id: "skill_fastapi",
    canonicalName: "FastAPI",
    displayName: "FastAPI",
    aliases: ["FastAPI", "Fast API"],
    category: "BACKEND",
    parentSkillId: "skill_python",
    relatedSkillIds: ["skill_python", "skill_rest_apis"],
    active: true,
  },
  {
    id: "skill_nestjs",
    canonicalName: "NestJS",
    displayName: "NestJS Framework",
    aliases: ["NestJS", "Nest.js", "Nest"],
    category: "BACKEND",
    parentSkillId: "skill_nodejs",
    relatedSkillIds: ["skill_nodejs", "skill_typescript"],
    active: true,
  },
  {
    id: "skill_django",
    canonicalName: "Django",
    displayName: "Django Framework",
    aliases: ["Django", "Django REST Framework", "DRF"],
    category: "BACKEND",
    parentSkillId: "skill_python",
    relatedSkillIds: ["skill_python", "skill_fastapi"],
    active: true,
  },

  // ──────────────── DATABASE ────────────────
  {
    id: "skill_mongodb",
    canonicalName: "MongoDB",
    displayName: "MongoDB (NoSQL)",
    aliases: ["MongoDB", "Mongo", "Mongoose"],
    category: "DATABASE",
    relatedSkillIds: ["skill_postgresql", "skill_redis"],
    active: true,
  },
  {
    id: "skill_postgresql",
    canonicalName: "PostgreSQL",
    displayName: "PostgreSQL",
    aliases: ["PostgreSQL", "Postgres", "Postgres DB", "PostgreSQL DB"],
    category: "DATABASE",
    parentSkillId: "skill_sql",
    relatedSkillIds: ["skill_sql", "skill_mongodb"],
    active: true,
  },
  {
    id: "skill_sql",
    canonicalName: "SQL",
    displayName: "SQL Relational Databases",
    aliases: ["SQL", "Relational Database", "RDBMS"],
    category: "DATABASE",
    relatedSkillIds: ["skill_postgresql", "skill_mysql"],
    active: true,
  },
  {
    id: "skill_redis",
    canonicalName: "Redis",
    displayName: "Redis In-Memory Cache",
    aliases: ["Redis", "Redis Cache"],
    category: "DATABASE",
    relatedSkillIds: ["skill_mongodb", "skill_postgresql"],
    active: true,
  },
  {
    id: "skill_firebase",
    canonicalName: "Firebase",
    displayName: "Google Firebase",
    aliases: ["Firebase", "Firestore", "Firebase Auth"],
    category: "DATABASE",
    relatedSkillIds: ["skill_mongodb", "skill_gcp"],
    active: true,
  },
  {
    id: "skill_mysql",
    canonicalName: "MySQL",
    displayName: "MySQL",
    aliases: ["MySQL", "My SQL"],
    category: "DATABASE",
    parentSkillId: "skill_sql",
    relatedSkillIds: ["skill_sql", "skill_postgresql"],
    active: true,
  },
  {
    id: "skill_dynamodb",
    canonicalName: "DynamoDB",
    displayName: "Amazon DynamoDB",
    aliases: ["DynamoDB", "Dynamo DB", "AWS DynamoDB"],
    category: "DATABASE",
    parentSkillId: "skill_aws",
    relatedSkillIds: ["skill_aws", "skill_mongodb"],
    active: true,
  },

  // ──────────────── CLOUD ────────────────
  {
    id: "skill_aws",
    canonicalName: "AWS",
    displayName: "Amazon Web Services (AWS)",
    aliases: ["AWS", "Amazon Web Services", "AWS Cloud", "Amazon AWS"],
    category: "CLOUD",
    relatedSkillIds: ["skill_docker", "skill_cloud_architecture", "skill_dynamodb"],
    active: true,
  },
  {
    id: "skill_cloud_architecture",
    canonicalName: "Cloud Architecture",
    displayName: "Cloud Architecture & Infrastructure",
    aliases: ["Cloud Architecture", "Cloud Infrastructure", "Cloud Computing"],
    category: "CLOUD",
    relatedSkillIds: ["skill_aws", "skill_gcp", "skill_azure"],
    active: true,
  },
  {
    id: "skill_docker",
    canonicalName: "Docker",
    displayName: "Docker Containerization",
    aliases: ["Docker", "Docker Container", "Docker Compose", "Containers"],
    category: "DEVOPS",
    relatedSkillIds: ["skill_kubernetes", "skill_aws", "skill_cicd"],
    active: true,
  },
  {
    id: "skill_vercel",
    canonicalName: "Vercel",
    displayName: "Vercel Deployment",
    aliases: ["Vercel", "Vercel Platform"],
    category: "CLOUD",
    relatedSkillIds: ["skill_nextjs", "skill_aws"],
    active: true,
  },
  {
    id: "skill_gcp",
    canonicalName: "GCP",
    displayName: "Google Cloud Platform (GCP)",
    aliases: ["GCP", "Google Cloud", "Google Cloud Platform"],
    category: "CLOUD",
    relatedSkillIds: ["skill_aws", "skill_firebase"],
    active: true,
  },
  {
    id: "skill_azure",
    canonicalName: "Azure",
    displayName: "Microsoft Azure",
    aliases: ["Azure", "Microsoft Azure", "MS Azure"],
    category: "CLOUD",
    relatedSkillIds: ["skill_aws", "skill_cloud_architecture"],
    active: true,
  },
  {
    id: "skill_serverless",
    canonicalName: "Serverless",
    displayName: "Serverless Architecture (Lambda/Functions)",
    aliases: ["Serverless", "AWS Lambda", "Cloud Functions", "Lambda"],
    category: "CLOUD",
    parentSkillId: "skill_aws",
    relatedSkillIds: ["skill_aws", "skill_cloud_architecture"],
    active: true,
  },

  // ──────────────── DEVOPS & TOOLS ────────────────
  {
    id: "skill_git",
    canonicalName: "Git",
    displayName: "Git Version Control",
    aliases: ["Git", "Version Control", "VCS"],
    category: "TOOLS",
    relatedSkillIds: ["skill_github", "skill_cicd"],
    active: true,
  },
  {
    id: "skill_github",
    canonicalName: "GitHub",
    displayName: "GitHub & Version Control",
    aliases: ["GitHub", "GitLab", "Bitbucket"],
    category: "TOOLS",
    parentSkillId: "skill_git",
    relatedSkillIds: ["skill_git", "skill_cicd"],
    active: true,
  },
  {
    id: "skill_cicd",
    canonicalName: "CI/CD",
    displayName: "CI/CD Automated Pipelines",
    aliases: ["CI/CD", "CICD", "CI-CD", "GitHub Actions", "GitLab CI", "Continuous Integration", "Continuous Deployment"],
    category: "DEVOPS",
    relatedSkillIds: ["skill_docker", "skill_git"],
    active: true,
  },
  {
    id: "skill_kubernetes",
    canonicalName: "Kubernetes",
    displayName: "Kubernetes (K8s)",
    aliases: ["Kubernetes", "K8s", "K8S"],
    category: "DEVOPS",
    parentSkillId: "skill_docker",
    relatedSkillIds: ["skill_docker", "skill_aws"],
    active: true,
  },
  {
    id: "skill_postman",
    canonicalName: "Postman",
    displayName: "Postman API Testing",
    aliases: ["Postman", "Postman API", "Swagger", "OpenAPI"],
    category: "TOOLS",
    relatedSkillIds: ["skill_rest_apis"],
    active: true,
  },
  {
    id: "skill_linux",
    canonicalName: "Linux",
    displayName: "Linux OS & Bash Scripting",
    aliases: ["Linux", "Ubuntu", "Debian", "Bash", "Shell Scripting", "Unix"],
    category: "DEVOPS",
    relatedSkillIds: ["skill_docker", "skill_git"],
    active: true,
  },

  // ──────────────── TESTING & AI/ML ────────────────
  {
    id: "skill_testing",
    canonicalName: "Automated Testing",
    displayName: "Automated Testing (Jest/Vitest)",
    aliases: ["Jest", "Vitest", "Unit Testing", "Integration Testing", "Cypress", "Playwright", "Mocha"],
    category: "TESTING",
    relatedSkillIds: ["skill_javascript", "skill_typescript"],
    active: true,
  },
  {
    id: "skill_aiml",
    canonicalName: "AI/ML",
    displayName: "Artificial Intelligence & Machine Learning",
    aliases: ["AI", "ML", "Machine Learning", "Artificial Intelligence", "LLMs", "Deep Learning", "TensorFlow", "PyTorch", "OpenAI API", "LangChain"],
    category: "AI_ML",
    parentSkillId: "skill_python",
    relatedSkillIds: ["skill_python"],
    active: true,
  },

  // ──────────────── MOBILE ────────────────
  {
    id: "skill_react_native",
    canonicalName: "React Native",
    displayName: "React Native Mobile",
    aliases: ["React Native", "ReactNative", "Expo"],
    category: "MOBILE",
    parentSkillId: "skill_react",
    relatedSkillIds: ["skill_react", "skill_typescript"],
    active: true,
  },
  {
    id: "skill_flutter",
    canonicalName: "Flutter",
    displayName: "Flutter (Dart)",
    aliases: ["Flutter", "Dart"],
    category: "MOBILE",
    relatedSkillIds: ["skill_mobile"],
    active: true,
  },
  {
    id: "skill_swift",
    canonicalName: "Swift",
    displayName: "Swift / iOS Development",
    aliases: ["Swift", "iOS", "SwiftUI", "Xcode"],
    category: "MOBILE",
    relatedSkillIds: ["skill_mobile"],
    active: true,
  },
  {
    id: "skill_kotlin",
    canonicalName: "Kotlin",
    displayName: "Kotlin / Android Development",
    aliases: ["Kotlin", "Android", "Android Studio"],
    category: "MOBILE",
    relatedSkillIds: ["skill_mobile"],
    active: true,
  },

  // ──────────────── CLOUD SERVICES & DEVOPS ────────────────
  {
    id: "skill_aws_s3",
    canonicalName: "AWS S3",
    displayName: "Amazon Simple Storage Service (S3)",
    aliases: ["S3", "AWS S3", "Amazon S3"],
    category: "CLOUD",
    parentSkillId: "skill_aws",
    relatedSkillIds: ["skill_aws", "skill_aws_ec2"],
    active: true,
  },
  {
    id: "skill_aws_ec2",
    canonicalName: "AWS EC2",
    displayName: "Amazon EC2 Elastic Compute",
    aliases: ["EC2", "AWS EC2", "Amazon EC2"],
    category: "CLOUD",
    parentSkillId: "skill_aws",
    relatedSkillIds: ["skill_aws", "skill_docker"],
    active: true,
  },
  {
    id: "skill_terraform",
    canonicalName: "Terraform",
    displayName: "Terraform (IaC)",
    aliases: ["Terraform", "HCL", "Infrastructure as Code", "IaC"],
    category: "DEVOPS",
    relatedSkillIds: ["skill_aws", "skill_docker"],
    active: true,
  },
  {
    id: "skill_nginx",
    canonicalName: "Nginx",
    displayName: "Nginx Web Server & Reverse Proxy",
    aliases: ["Nginx", "NGINX", "Reverse Proxy"],
    category: "DEVOPS",
    relatedSkillIds: ["skill_linux", "skill_docker"],
    active: true,
  },

  // ──────────────── SECURITY & DATABASES ────────────────
  {
    id: "skill_security",
    canonicalName: "Cybersecurity & OAuth",
    displayName: "Security, OAuth & Auth Standards",
    aliases: ["OAuth", "OAuth 2.0", "Security", "Cybersecurity", "OWASP", "Encryption", "Auth0"],
    category: "SECURITY",
    relatedSkillIds: ["skill_jwt"],
    active: true,
  },
  {
    id: "skill_sqlite",
    canonicalName: "SQLite",
    displayName: "SQLite Database",
    aliases: ["SQLite", "SQLite3"],
    category: "DATABASE",
    parentSkillId: "skill_sql",
    relatedSkillIds: ["skill_sql", "skill_postgresql"],
    active: true,
  },
  {
    id: "skill_dynamodb",
    canonicalName: "DynamoDB",
    displayName: "Amazon DynamoDB (NoSQL)",
    aliases: ["DynamoDB", "AWS DynamoDB", "Amazon DynamoDB"],
    category: "DATABASE",
    parentSkillId: "skill_aws",
    relatedSkillIds: ["skill_mongodb", "skill_aws"],
    active: true,
  },
];
